### ISSUE TITLE
VirusTotal

### ISSUE THREAD

**Issue by ppvnf** [oleg-shilo/multiclip#3]
https://www.virustotal.com/gui/file/c4e1759f12c7233f91e34639517392eb4b728c2d626784007b78c8061ded6456/detection

I believe it is just a false positive, but Bitdefender, Avast and McAfee are detecting this app as malware.

**Comment by oleg-shilo** [comment]
yes, I know :(

It is becoming increasingly disturbing. More and more antimaleware vendors are trying to convince potential customers they are doing a great job by demonstrating a higher level of positive detection without taking any responsibility for the quality of the detection and business impact of false positives.

My own business experience - the whole team was blocked for one day because that specific vendor (present on virustotal) decided that an old C++ compiler and command-prompt are the threats. :o(

During my experiments (5 Sep 2021) I found that an empty (just created) .NET Framework console app triggers 2 positives. Adding any resource file (no actual resources but an empty resx file) bumps it to 7 false positives.

I am lucky my products are open source so anyone can inspect the source code and see that the products are safe. But if they were close-source products then I have no chance of convincing my users/customers that I am not a monster.

**Comment by ppvnf** [comment]
I can confirm it. I made a simple and harmless VBS file and It really feels like some AV vendors are using a whitelist for popular software and blocking all the rest. Maybe you can contact the vendors and ask them to whitelist your apps, but i know this is time consuming.
https://www.virustotal.com/gui/file/0c14e6e6accffa81edec63307e99e004d5cd4085f8ef989a494d9645bfc1e8cb?nocache=1

**Comment by oleg-shilo** [comment]
TBH it's not even time-consuming but plain impossible. None of 66 VirusTotal providers allowed any feedback channel. 
I really do not see a way out. 

Ironically these providers soot themselves in the foot. By allowing so controversial AI algorithms they degrade the quality of the detection and as a result erode the customer trust in their own capabilities.

**Comment by ppvnf** [comment]
> TBH it's not even time-consuming but plain impossible. None of 66 VirusTotal providers allowed any feedback channel. I really do not see a way out.

Just a little tip. I've found out this webpage explaining how to contact AV vendors: https://www.techsupportalert.com/how-to-report-malware-or-false-positives-to-multiple-antivirus-vendors/

**Comment by oleg-shilo** [comment]
Txs
